### ISSUE TITLE
How to enable Projects section in Hugo Introduction theme?

### ISSUE THREAD

**Issue by RaymondSeyf** [vickylaixy/hugo-theme-introduction#2]
Thanks for sharing this beautiful minimal hugo theme with the community.
I have a question about showing my projects inside my homepage.
I know that I should config showProjects variable in config.toml but how I should customize and show content for Homepage Projects section?
I need to show more than 3 projects in my homepage, And I need description below the photo's of projects.

Thank you for your help

**Comment by vickylaixy** [comment]
In the spirit of minimalism, it's not possible to show more projects or add more text to the projects section at the moment. :) Maybe in a future version if there's enough interest.

At the moment, set "showProjects" in your config file to "true" and fill out the params as in "/exampleSite/config.toml"

Nice website btw!

**Comment by Heirak** [comment]
I would love to see this functionality added as well :) Email sent expressing interest
